<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>PGame-UTSLManager</AssemblyName>
    <RootNamespace>PGame.UTSLManager</RootNamespace>
    <AssemblyTitle>PGame-UTSLManager</AssemblyTitle>
    <Product>PGame-UTSLManager</Product>
    <Version>1.2.0</Version>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <None Update="manager.example.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
